version: '3'
services:

  robot-controller:
    build:
      context: ./app/server
    ports:
      - "8080:8080"
      - "50051:50051"
    networks:
      - robot-network

  robot1:
    build:
      context: ./app/robot
      dockerfile: Dockerfile.robot1
    depends_on:
      - robot-controller
    networks:
      - robot-network

  robot2:
    build:
      context: ./app/robot
      dockerfile: Dockerfile.robot2
    depends_on:
      - robot-controller
    networks:
      - robot-network

  robot3:
    build:
      context: ./app/robot
      dockerfile: Dockerfile.robot3
    depends_on:
      - robot-controller
    networks:
      - robot-network

  robot4:
    build:
      context: ./app/robot
      dockerfile: Dockerfile.robot4
    depends_on:
      - robot-controller
    networks:
      - robot-network

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - robot-network
  

networks:
  robot-network:
