// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server.proto
#ifndef GRPC_server_2eproto__INCLUDED
#define GRPC_server_2eproto__INCLUDED

#include "server.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

// Definition des Dienstes
class RobotControl final {
 public:
  static constexpr char const* service_full_name() {
    return "RobotControl";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration& request, ::RobotStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>> AsyncRegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>>(AsyncRegisterRobotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>> PrepareAsyncRegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>>(PrepareAsyncRegisterRobotRaw(context, request, cq));
    }
    virtual ::grpc::Status GetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration& request, ::RobotStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>> AsyncGetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>>(AsyncGetRobotStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>> PrepareAsyncGetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>>(PrepareAsyncGetRobotStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status SetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::RobotStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>> AsyncSetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>>(AsyncSetRobotStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>> PrepareAsyncSetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>>(PrepareAsyncSetRobotStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus* request, ::RobotStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus* request, ::RobotStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>* AsyncRegisterRobotRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>* PrepareAsyncRegisterRobotRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>* AsyncGetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>* PrepareAsyncGetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>* AsyncSetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RobotStatus>* PrepareAsyncSetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration& request, ::RobotStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>> AsyncRegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>>(AsyncRegisterRobotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>> PrepareAsyncRegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>>(PrepareAsyncRegisterRobotRaw(context, request, cq));
    }
    ::grpc::Status GetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration& request, ::RobotStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>> AsyncGetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>>(AsyncGetRobotStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>> PrepareAsyncGetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>>(PrepareAsyncGetRobotStatusRaw(context, request, cq));
    }
    ::grpc::Status SetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::RobotStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>> AsyncSetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>>(AsyncSetRobotStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>> PrepareAsyncSetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RobotStatus>>(PrepareAsyncSetRobotStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, std::function<void(::grpc::Status)>) override;
      void RegisterRobot(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, std::function<void(::grpc::Status)>) override;
      void GetRobotStatus(::grpc::ClientContext* context, const ::RobotRegistration* request, ::RobotStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus* request, ::RobotStatus* response, std::function<void(::grpc::Status)>) override;
      void SetRobotStatus(::grpc::ClientContext* context, const ::RobotSetStatus* request, ::RobotStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::RobotStatus>* AsyncRegisterRobotRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RobotStatus>* PrepareAsyncRegisterRobotRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RobotStatus>* AsyncGetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RobotStatus>* PrepareAsyncGetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotRegistration& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RobotStatus>* AsyncSetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RobotStatus>* PrepareAsyncSetRobotStatusRaw(::grpc::ClientContext* context, const ::RobotSetStatus& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterRobot_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRobotStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_SetRobotStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterRobot(::grpc::ServerContext* context, const ::RobotRegistration* request, ::RobotStatus* response);
    virtual ::grpc::Status GetRobotStatus(::grpc::ServerContext* context, const ::RobotRegistration* request, ::RobotStatus* response);
    virtual ::grpc::Status SetRobotStatus(::grpc::ServerContext* context, const ::RobotSetStatus* request, ::RobotStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterRobot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterRobot() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterRobot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterRobot(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterRobot(::grpc::ServerContext* context, ::RobotRegistration* request, ::grpc::ServerAsyncResponseWriter< ::RobotStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRobotStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotStatus(::grpc::ServerContext* context, ::RobotRegistration* request, ::grpc::ServerAsyncResponseWriter< ::RobotStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetRobotStatus() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotSetStatus* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRobotStatus(::grpc::ServerContext* context, ::RobotSetStatus* request, ::grpc::ServerAsyncResponseWriter< ::RobotStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterRobot<WithAsyncMethod_GetRobotStatus<WithAsyncMethod_SetRobotStatus<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterRobot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterRobot() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RobotRegistration, ::RobotStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RobotRegistration* request, ::RobotStatus* response) { return this->RegisterRobot(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterRobot(
        ::grpc::MessageAllocator< ::RobotRegistration, ::RobotStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RobotRegistration, ::RobotStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterRobot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterRobot(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterRobot(
      ::grpc::CallbackServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRobotStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::RobotRegistration, ::RobotStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RobotRegistration* request, ::RobotStatus* response) { return this->GetRobotStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetRobotStatus(
        ::grpc::MessageAllocator< ::RobotRegistration, ::RobotStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RobotRegistration, ::RobotStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetRobotStatus() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::RobotSetStatus, ::RobotStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RobotSetStatus* request, ::RobotStatus* response) { return this->SetRobotStatus(context, request, response); }));}
    void SetMessageAllocatorFor_SetRobotStatus(
        ::grpc::MessageAllocator< ::RobotSetStatus, ::RobotStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RobotSetStatus, ::RobotStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotSetStatus* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetRobotStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::RobotSetStatus* /*request*/, ::RobotStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterRobot<WithCallbackMethod_GetRobotStatus<WithCallbackMethod_SetRobotStatus<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterRobot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterRobot() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterRobot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterRobot(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRobotStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetRobotStatus() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotSetStatus* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterRobot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterRobot() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterRobot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterRobot(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterRobot(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRobotStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRobotStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetRobotStatus() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotSetStatus* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRobotStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterRobot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterRobot() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterRobot(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterRobot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterRobot(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterRobot(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRobotStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRobotStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRobotStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetRobotStatus() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetRobotStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotSetStatus* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetRobotStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterRobot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterRobot() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RobotRegistration, ::RobotStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RobotRegistration, ::RobotStatus>* streamer) {
                       return this->StreamedRegisterRobot(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterRobot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterRobot(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterRobot(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RobotRegistration,::RobotStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRobotStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RobotRegistration, ::RobotStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RobotRegistration, ::RobotStatus>* streamer) {
                       return this->StreamedGetRobotStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotRegistration* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRobotStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RobotRegistration,::RobotStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetRobotStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetRobotStatus() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RobotSetStatus, ::RobotStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RobotSetStatus, ::RobotStatus>* streamer) {
                       return this->StreamedSetRobotStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetRobotStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetRobotStatus(::grpc::ServerContext* /*context*/, const ::RobotSetStatus* /*request*/, ::RobotStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetRobotStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RobotSetStatus,::RobotStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterRobot<WithStreamedUnaryMethod_GetRobotStatus<WithStreamedUnaryMethod_SetRobotStatus<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterRobot<WithStreamedUnaryMethod_GetRobotStatus<WithStreamedUnaryMethod_SetRobotStatus<Service > > > StreamedService;
};


#endif  // GRPC_server_2eproto__INCLUDED
