// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

#include "server.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr RobotStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : is_active_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RobotStatus::RobotStatus(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RobotStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotStatusDefaultTypeInternal() {}
  union {
    RobotStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotStatusDefaultTypeInternal _RobotStatus_default_instance_;

inline constexpr RobotSetStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : robot_id_{0},
        is_active_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RobotSetStatus::RobotSetStatus(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RobotSetStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotSetStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotSetStatusDefaultTypeInternal() {}
  union {
    RobotSetStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotSetStatusDefaultTypeInternal _RobotSetStatus_default_instance_;

inline constexpr RobotRegistration::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : robot_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        robot_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RobotRegistration::RobotRegistration(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RobotRegistrationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotRegistrationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotRegistrationDefaultTypeInternal() {}
  union {
    RobotRegistration _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotRegistrationDefaultTypeInternal _RobotRegistration_default_instance_;
static ::_pb::Metadata file_level_metadata_server_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_server_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_2eproto = nullptr;
const ::uint32_t TableStruct_server_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RobotStatus, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RobotStatus, _impl_.is_active_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RobotRegistration, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RobotRegistration, _impl_.robot_id_),
    PROTOBUF_FIELD_OFFSET(::RobotRegistration, _impl_.robot_name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RobotSetStatus, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RobotSetStatus, _impl_.robot_id_),
    PROTOBUF_FIELD_OFFSET(::RobotSetStatus, _impl_.is_active_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::RobotStatus)},
        {9, -1, -1, sizeof(::RobotRegistration)},
        {19, -1, -1, sizeof(::RobotSetStatus)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_RobotStatus_default_instance_._instance,
    &::_RobotRegistration_default_instance_._instance,
    &::_RobotSetStatus_default_instance_._instance,
};
const char descriptor_table_protodef_server_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014server.proto\" \n\013RobotStatus\022\021\n\tis_acti"
    "ve\030\001 \001(\010\"9\n\021RobotRegistration\022\020\n\010robot_i"
    "d\030\001 \001(\005\022\022\n\nrobot_name\030\002 \001(\t\"5\n\016RobotSetS"
    "tatus\022\020\n\010robot_id\030\001 \001(\005\022\021\n\tis_active\030\002 \001"
    "(\0102\246\001\n\014RobotControl\0221\n\rRegisterRobot\022\022.R"
    "obotRegistration\032\014.RobotStatus\0222\n\016GetRob"
    "otStatus\022\022.RobotRegistration\032\014.RobotStat"
    "us\022/\n\016SetRobotStatus\022\017.RobotSetStatus\032\014."
    "RobotStatusb\006proto3"
};
static ::absl::once_flag descriptor_table_server_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_server_2eproto = {
    false,
    false,
    339,
    descriptor_table_protodef_server_2eproto,
    "server.proto",
    &descriptor_table_server_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_server_2eproto::offsets,
    file_level_metadata_server_2eproto,
    file_level_enum_descriptors_server_2eproto,
    file_level_service_descriptors_server_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_server_2eproto_getter() {
  return &descriptor_table_server_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_server_2eproto(&descriptor_table_server_2eproto);
// ===================================================================

class RobotStatus::_Internal {
 public:
};

RobotStatus::RobotStatus(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RobotStatus)
}
RobotStatus::RobotStatus(
    ::google::protobuf::Arena* arena, const RobotStatus& from)
    : RobotStatus(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RobotStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RobotStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_active_ = {};
}
RobotStatus::~RobotStatus() {
  // @@protoc_insertion_point(destructor:RobotStatus)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RobotStatus::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RobotStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotStatus)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.is_active_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RobotStatus::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> RobotStatus::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RobotStatus_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool is_active = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RobotStatus, _impl_.is_active_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.is_active_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_active = 1;
    {PROTOBUF_FIELD_OFFSET(RobotStatus, _impl_.is_active_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RobotStatus::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool is_active = 1;
  if (this->_internal_is_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_is_active(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotStatus)
  return target;
}

::size_t RobotStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool is_active = 1;
  if (this->_internal_is_active() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RobotStatus::_class_data_ = {
    RobotStatus::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RobotStatus::GetClassData() const {
  return &_class_data_;
}

void RobotStatus::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RobotStatus*>(&to_msg);
  auto& from = static_cast<const RobotStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_is_active() != 0) {
    _this->_internal_set_is_active(from._internal_is_active());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotStatus::CopyFrom(const RobotStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RobotStatus::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RobotStatus::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RobotStatus::InternalSwap(RobotStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.is_active_, other->_impl_.is_active_);
}

::google::protobuf::Metadata RobotStatus::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_2eproto_getter, &descriptor_table_server_2eproto_once,
      file_level_metadata_server_2eproto[0]);
}
// ===================================================================

class RobotRegistration::_Internal {
 public:
};

RobotRegistration::RobotRegistration(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RobotRegistration)
}
inline PROTOBUF_NDEBUG_INLINE RobotRegistration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : robot_name_(arena, from.robot_name_),
        _cached_size_{0} {}

RobotRegistration::RobotRegistration(
    ::google::protobuf::Arena* arena,
    const RobotRegistration& from)
    : ::google::protobuf::Message(arena) {
  RobotRegistration* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.robot_id_ = from._impl_.robot_id_;

  // @@protoc_insertion_point(copy_constructor:RobotRegistration)
}
inline PROTOBUF_NDEBUG_INLINE RobotRegistration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : robot_name_(arena),
        _cached_size_{0} {}

inline void RobotRegistration::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.robot_id_ = {};
}
RobotRegistration::~RobotRegistration() {
  // @@protoc_insertion_point(destructor:RobotRegistration)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RobotRegistration::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.robot_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RobotRegistration::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotRegistration)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.robot_name_.ClearToEmpty();
  _impl_.robot_id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RobotRegistration::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2> RobotRegistration::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RobotRegistration_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string robot_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RobotRegistration, _impl_.robot_name_)}},
    // int32 robot_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RobotRegistration, _impl_.robot_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RobotRegistration, _impl_.robot_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 robot_id = 1;
    {PROTOBUF_FIELD_OFFSET(RobotRegistration, _impl_.robot_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string robot_name = 2;
    {PROTOBUF_FIELD_OFFSET(RobotRegistration, _impl_.robot_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\12\0\0\0\0\0"
    "RobotRegistration"
    "robot_name"
  }},
};

::uint8_t* RobotRegistration::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotRegistration)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 robot_id = 1;
  if (this->_internal_robot_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_robot_id(), target);
  }

  // string robot_name = 2;
  if (!this->_internal_robot_name().empty()) {
    const std::string& _s = this->_internal_robot_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "RobotRegistration.robot_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotRegistration)
  return target;
}

::size_t RobotRegistration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotRegistration)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string robot_name = 2;
  if (!this->_internal_robot_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_robot_name());
  }

  // int32 robot_id = 1;
  if (this->_internal_robot_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_robot_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RobotRegistration::_class_data_ = {
    RobotRegistration::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RobotRegistration::GetClassData() const {
  return &_class_data_;
}

void RobotRegistration::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RobotRegistration*>(&to_msg);
  auto& from = static_cast<const RobotRegistration&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotRegistration)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_robot_name().empty()) {
    _this->_internal_set_robot_name(from._internal_robot_name());
  }
  if (from._internal_robot_id() != 0) {
    _this->_internal_set_robot_id(from._internal_robot_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotRegistration::CopyFrom(const RobotRegistration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotRegistration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RobotRegistration::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RobotRegistration::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RobotRegistration::InternalSwap(RobotRegistration* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.robot_name_, &other->_impl_.robot_name_, arena);
        swap(_impl_.robot_id_, other->_impl_.robot_id_);
}

::google::protobuf::Metadata RobotRegistration::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_2eproto_getter, &descriptor_table_server_2eproto_once,
      file_level_metadata_server_2eproto[1]);
}
// ===================================================================

class RobotSetStatus::_Internal {
 public:
};

RobotSetStatus::RobotSetStatus(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RobotSetStatus)
}
RobotSetStatus::RobotSetStatus(
    ::google::protobuf::Arena* arena, const RobotSetStatus& from)
    : RobotSetStatus(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RobotSetStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RobotSetStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, robot_id_),
           0,
           offsetof(Impl_, is_active_) -
               offsetof(Impl_, robot_id_) +
               sizeof(Impl_::is_active_));
}
RobotSetStatus::~RobotSetStatus() {
  // @@protoc_insertion_point(destructor:RobotSetStatus)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RobotSetStatus::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RobotSetStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:RobotSetStatus)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.robot_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_active_) -
      reinterpret_cast<char*>(&_impl_.robot_id_)) + sizeof(_impl_.is_active_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RobotSetStatus::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> RobotSetStatus::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RobotSetStatus_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool is_active = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RobotSetStatus, _impl_.is_active_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RobotSetStatus, _impl_.is_active_)}},
    // int32 robot_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RobotSetStatus, _impl_.robot_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RobotSetStatus, _impl_.robot_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 robot_id = 1;
    {PROTOBUF_FIELD_OFFSET(RobotSetStatus, _impl_.robot_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool is_active = 2;
    {PROTOBUF_FIELD_OFFSET(RobotSetStatus, _impl_.is_active_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RobotSetStatus::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RobotSetStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 robot_id = 1;
  if (this->_internal_robot_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_robot_id(), target);
  }

  // bool is_active = 2;
  if (this->_internal_is_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_is_active(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RobotSetStatus)
  return target;
}

::size_t RobotSetStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RobotSetStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 robot_id = 1;
  if (this->_internal_robot_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_robot_id());
  }

  // bool is_active = 2;
  if (this->_internal_is_active() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RobotSetStatus::_class_data_ = {
    RobotSetStatus::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RobotSetStatus::GetClassData() const {
  return &_class_data_;
}

void RobotSetStatus::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RobotSetStatus*>(&to_msg);
  auto& from = static_cast<const RobotSetStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RobotSetStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_robot_id() != 0) {
    _this->_internal_set_robot_id(from._internal_robot_id());
  }
  if (from._internal_is_active() != 0) {
    _this->_internal_set_is_active(from._internal_is_active());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RobotSetStatus::CopyFrom(const RobotSetStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RobotSetStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RobotSetStatus::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RobotSetStatus::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RobotSetStatus::InternalSwap(RobotSetStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RobotSetStatus, _impl_.is_active_)
      + sizeof(RobotSetStatus::_impl_.is_active_)
      - PROTOBUF_FIELD_OFFSET(RobotSetStatus, _impl_.robot_id_)>(
          reinterpret_cast<char*>(&_impl_.robot_id_),
          reinterpret_cast<char*>(&other->_impl_.robot_id_));
}

::google::protobuf::Metadata RobotSetStatus::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_2eproto_getter, &descriptor_table_server_2eproto_once,
      file_level_metadata_server_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
