// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RobotController.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class RobotControllerHandler : virtual public RobotControllerIf {
 public:
  RobotControllerHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void registerRobot(const int32_t id, const std::string& name) {
    // Your implementation goes here
    printf("registerRobot\n");
  }

  bool checkRobotHealth(const int32_t id) {
    // Your implementation goes here
    printf("checkRobotHealth\n");
  }

  void electionResult(const int32_t id) {
    // Your implementation goes here
    printf("electionResult\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<RobotControllerHandler> handler(new RobotControllerHandler());
  ::std::shared_ptr<TProcessor> processor(new RobotControllerProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

